version: '3.8'

services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
 
volumes:
  redis_data:

